# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Update dist
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  update-dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.SYNCED_GITHUB_TOKEN_REPO }}
          repository: ${{ github.event.client_payload.pull_request.head.repo.full_name }}
          ref: ${{ github.event.client_payload.pull_request.head.ref }}
      - run: npm ci
      - name: Update dist
        run: |
          npm run build
          git config --global user.name 'googlemaps-bot'
          git config --global user.email 'googlemaps-bot@google.com'
          git add -f dist
          git commit -m "chore: update dist folder [skip ci]" || true
          git push origin
